---
service_dir: "{{ project_dir }}/gitlab"

gitlab_image_tag: 17.7.0-ce.0

# gitlab domain
gitlab_main_domain: "git.{{ main_domain }}"
gitlab_registry_domain: "reg.{{ main_domain }}"

# minio information
minio_api_endpoint: https://min.rahbia.mecan.ir
minio_gitlab_backup_bucket: gitlab-backup